### ISSUE TITLE
Correção do arquivo yarn-site.xml erro no comando sed

### ISSUE THREAD

**Issue by jcr0ch4** [felipedoamarals/Aceleracao_Global_Dev4_Everis#1]
O comando para corrigir a gravação do log esta  incompleto.
O comando sed precisa do parâmetro a ser pesquisado e depois o que será alterado.
O comando deve ser esse:
sudo sed -i 's|hdfs://|hdfs://bigdata-srv:8020/|g' /etc/hadoop/conf/yarn-site.xml

**Comment by felipedoamarals** [comment]
Perfeito @jcr0ch4 ! Obrigado pela contribuição.
